services:
  web:
    build: .
    restart: always
    networks:
      - wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${DEBUG_MODE:-1}
    volumes:
      - .:/var/www/html/wp-content/themes/aydev

  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${FORWARD_PORT:-3306}:3306
    networks:
      - wordpress
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

networks:
  wordpress:
volumes:
  db: